version: '2'
services:
    samaautov1-app:
        image: samaautov1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samaautov1-mysql:3306/samaautov1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=samaautov1-elasticsearch:9300
        ports:
            - 8080:8080
    samaautov1-mysql:
        extends:
            file: mysql.yml
            service: samaautov1-mysql
    samaautov1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: samaautov1-elasticsearch
